IndexaWeb.Intranet/Controllers/VisitHeadersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IndexaWeb.Intranet;
using IndexaWeb.Intranet.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity.Validation;
using System.Net.Mail;
using System.Net.Mime;

namespace IndexaWeb.Intranet.Controllers
{
    [Authorize]
    public class VisitHeadersController : Controller
    {
        private IndexaWebModel db = new IndexaWebModel();

        // GET: VisitHeaders
        public async Task<ActionResult> Index()
        {
            var visitHeader = db.VisitHeader.Include(v => v.Customer).Include(v => v.Employee).Include(v => v.Location).Include(s => s.StatusVisit);
            if (User.IsInRole("Soporte"))
                visitHeader = visitHeader.Where(v => v.Employee.UserName == User.Identity.Name);
            if (User.IsInRole("Cliente"))
                visitHeader = visitHeader.Where(v => v.Customer.Representative.Where(x => x.UserName == User.Identity.Name).FirstOrDefault().CustomerId == v.CustomerId);
            return View(await visitHeader.Where(v => v.Active == true).ToListAsync());
        }
        
        public ActionResult GetLocationsByCustomerId(int id)
        {
            var locations = db.Location.Where(m => m.CustomerId == id).Select(p=> new { LocationId = p.LocationId, Description = p.Description });
            return Json(locations.ToList(), JsonRequestBehavior.AllowGet);
        }
        // GET: VisitHeaders/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            VisitHeader visitHeader = await db.VisitHeader.FindAsync(id);
            if (visitHeader == null)
            {
                return HttpNotFound();
            }
            ViewBag.StatusVisit = visitHeader.StatusVisitId;
            ViewBag.ReclaimExists = visitHeader.Reclaims.Count > 0;
            if (ViewBag.ReclaimExists)
                visitHeader.Reclaims = db.Reclaim.Where(r => r.VisitHeaderId == visitHeader.VisitHeaderId).ToList();
            ViewBag.VisitHeaderId = visitHeader.VisitHeaderId;
            ViewBag.isAdminOrCustomer = User.IsInRole("Administrador") || User.IsInRole("Cliente");
            if (visitHeader.CreatedBy == User.Identity.Name || ViewBag.isAdminOrCustomer)
                return View(visitHeader);
            return RedirectToAction("Index");
        }

        private void SaveStatusVisitHistory(int newStatus, int visitHeaderId)
        {
            StatusVisitHistory statusVisitHistory = new StatusVisitHistory();
            statusVisitHistory.StatusVisitId = newStatus;
            statusVisitHistory.VisitHeaderId = visitHeaderId;
            statusVisitHistory.CreatedBy = User.Identity.Name;
            statusVisitHistory.CreatedDate = DateTime.Now;
            db.StatusVisitHistory.Add(statusVisitHistory);
            db.SaveChanges();
        }

        

        public string GetIP4Address()
        {
            string IP4Address = String.Empty;

            foreach (IPAddress ipa in Dns.GetHostAddresses(Request.ServerVariables["REMOTE_ADDR"].ToString()))
            {
                if (ipa.AddressFamily.ToString() == "InterNetwork")
                {
                    IP4Address = ipa.ToString();
                    break;
                }
            }

            if (IP4Address != String.Empty)
            {
                return IP4Address;
            }

            foreach (IPAddress IPA in Dns.GetHostAddresses(Dns.GetHostName()))
            {
                if (IPA.AddressFamily.ToString() == "InterNetwork")
                {
                    IP4Address = IPA.ToString();
                    break;
                }
            }

            return IP4Address;
        }

        public void SendConfirmationMail(VisitHeader visitHeader)
        {
            //string htmlBody = "<img src = '~/Content/images/logo.jpg' />";
            //AlternateView avHtml = AlternateView.CreateAlternateViewFromString
            //   (htmlBody, null, MediaTypeNames.Text.Html);

            //LinkedResource inline = new LinkedResource(Server.MapPath("/IndexaWeb.Intranet/Content/images/logo.jpg"), MediaTypeNames.Image.Jpeg);
            //inline.ContentId = Guid.NewGuid().ToString();
            //avHtml.LinkedResources.Add(inline);


            string supervisorMailAddress = (from j in db.Employee
                                            join k in db.AspNetUsers
                                            on j.UserName equals k.UserName
                                            where j.EmployeeId == visitHeader.Employee.SupervisorId
                                            select k.Email).FirstOrDefault();
            List<string> representativesMailAddresses = (from j in db.Representative
                                                     join k in db.AspNetUsers
                                                     on j.UserName equals k.UserName
                                                     where j.CustomerId == visitHeader.CustomerId
                                                     select k.Email).ToList();
            
            MailMessage mail = new MailMessage();
            Attachment att = new Attachment(Server.MapPath("/IndexaWeb.Intranet/Content/images/logo.jpg"));
            //mail.AlternateViews.Add(avHtml);
            mail.Attachments.Add(att);
            SmtpClient client = new SmtpClient();
            client.Port = 587;
            client.DeliveryMethod = SmtpDeliveryMethod.Network;
            client.UseDefaultCredentials = true;
            client.EnableSsl = true;
            client.Host = "smtp.gmail.com";
            client.Credentials = new NetworkCredential("mperez@indexa.com.ve", "N1c0l3.,");
            mail.From = new MailAddress("mperez@indexa.com.ve");
            foreach (var email in representativesMailAddresses)
            {
                mail.To.Add(new MailAddress(email));
            }
            if (supervisorMailAddress != null)
                mail.To.Add(new MailAddress(supervisorMailAddress));
            mail.To.Add(new MailAddress(visitHeader.Employee.Email));
            mail.Subject = "Confirmación de visita";
            mail.IsBodyHtml = true;
            mail.Body = "<p>Buen día, por medio de la presente el soportista " + visitHeader.Employee.EmployeeName + " indica que ha realizado una visita en </ br>" +
                " su empresa, por favor verifique la información de la visita en el siguiente <a href='192.168.100.2/IndexaWeb/VisitHeaders/Details/" + visitHeader.VisitHeaderId + "'>enlace</a></ br>" +
                "</ br>Esto es una Prueba</p></ br>"+
                "Control de Visitas INDEXA IT Solutions</p>" +
                "<footer class='panel-footer'>" +
                "<p>" + DateTime.Now.ToLongDateString() + " " + DateTime.Now.ToLongTimeString() + "</ p>" +
                "</ footer >";
            client.Send(mail);

        }

        // GET: VisitHeaders/Create
        [Authorize(Order = 1, Roles = "Administrador, Soporte")]
        public ActionResult Create()
        {
            //ViewBag.CustomerId = new SelectList(db.Customer, "CustomerId", "Name");
            ViewBag.LocationId = new SelectList(db.Location, "LocationId", "Description");
            return View();
        }
        // POST: VisitHeaders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Order = 1, Roles = "Administrador, Soporte")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "CustomerId,LocationId,VisitDate,ArrivalTime,DepatureTime")] VisitHeader visitHeader)
        {
            
            if (ModelState.IsValid)
            {
                visitHeader.EmployeeId = db.Employee.Where(e => e.UserName == User.Identity.Name).Select(e => e.EmployeeId).FirstOrDefault();
                visitHeader.StatusVisitId = 1;
                visitHeader.IpAddress = GetIP4Address();
                visitHeader.Active = true;
                visitHeader.CreatedBy = User.Identity.Name;
                visitHeader.CreatedDate = DateTime.Now;
                try
                {
                    db.VisitHeader.Add(visitHeader);
                    await db.SaveChangesAsync();
                }
                catch (DbEntityValidationException e)
                {
                    foreach (var error in e.EntityValidationErrors)
                    {
                        foreach (var thisError in error.ValidationErrors)
                        {
                            ModelState.AddModelError(thisError.PropertyName, thisError.ErrorMessage);
                        }
                    }
                    //ViewBag.CustomerId = new SelectList(db.Customer, "CustomerId", "Name", visitHeader.CustomerId);
                    ViewBag.LocationId = new SelectList(db.Location, "LocationId", "Description", visitHeader.LocationId);
                    return View(visitHeader);
                }      
                SaveStatusVisitHistory(visitHeader.StatusVisitId, visitHeader.VisitHeaderId);

                return RedirectToAction("Edit", new { id = visitHeader.VisitHeaderId });
            }

            ViewBag.CustomerId = new SelectList(db.Customer, "CustomerId", "Name", visitHeader.CustomerId);
            ViewBag.LocationId = new SelectList(db.Location, "LocationId", "Description", visitHeader.LocationId);
            return View(visitHeader);
        }

        [Authorize(Order = 1, Roles = "Administrador, Soporte")]
        // GET: VisitHeaders/Edit/5

IndexaWeb.Intranet/Views/VisitHeaders/ConfirmVisit.cshtml
@model IndexaWeb.Intranet.VisitHeader

@{
    ViewBag.Title = "Confirmar Visita";
}

<h2>Aprobar</h2>


@using (Html.BeginForm("ConfirmVisit","VisitHeaders"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Visita</h4>
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VisitHeaderId)
        @Html.HiddenFor(model => model.CustomerId)
        @Html.HiddenFor(model => model.LocationId)
        @Html.HiddenFor(model => model.EmployeeId)
        @Html.HiddenFor(model => model.VisitDate)
        @Html.HiddenFor(model => model.ArrivalTime)
        @Html.HiddenFor(model => model.DepatureTime)
        @Html.HiddenFor(model => model.CreatedBy)
        @Html.HiddenFor(model => model.CreatedDate)
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Employee.EmployeeName, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Customer.Name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location.Description, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VisitDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VisitDate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.VisitDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ArrivalTime, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ArrivalTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepatureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepatureTime, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.DepatureTime, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreatedDate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.CreatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedBy, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ModifiedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ModifiedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ModifiedDate, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                @Html.ValidationMessageFor(model => model.ModifiedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StatusVisitId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StatusVisitId, (SelectList)ViewBag.StatusVisit, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StatusVisitId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" >
                <input type="submit" value="Confirmar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver al listado", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('#datepicker').datetimepicker({
            format: "MM-DD-YYYY"
        });
        $('#m_arrivalTime,#m_departureTime').datetimepicker({
            format: 'HH:mm'
        });
    </script>
}

IndexaWeb.Intranet/Views/VisitHeaders/Details.cshtml
@model IndexaWeb.Intranet.VisitHeader

@{
    ViewBag.Title = "Detalles Visita";
}

<h2>Detalles</h2>

<div>
    <h4>Visita</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Customer.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Customer.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Employee.EmployeeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.EmployeeName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Location.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.Description)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.VisitDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VisitDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepatureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepatureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatusVisit.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatusVisit.Name, new { id = "statusVisitName" } )
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>
    @if (Model.StatusVisitId == 1 && (User.IsInRole("Soporte") || User.IsInRole("Administrador")))
    {
        <div class="form-group">
            @Html.ActionLink("Editar", "Edit", new { id = Model.VisitHeaderId })
        </div>
    }

    @if (ViewBag.isAdminOrCustomer == true && Model.StatusVisitId != 3)
    {
        <div class="form-group">
            @Html.ActionLink("Aprobar Visita", "ConfirmVisit", new { id = Model.VisitHeaderId }, new { @class = "btn btn-default" })
        </div>
    }

    <div class="form-group">
        <h4>Actividades Realizadas</h4>
        @Html.Partial("_IndexVisitDetails", Model.VisitDetail)
    </div>
    @if (!ViewBag.ReclaimExists && Model.StatusVisitId == 4 && ViewBag.isAdminOrCustomer == true)
    {
        <div class="form-group">
            @Html.ActionLink("Agregar Reclamo", "AddReclaim", "VisitHeaders", new { id = ViewBag.VisitHeaderId }, new { id = "addReclaimLink", @class = "btn btn-default modal-link", title = "Agregar Reclamo", data_toggle = "modal", data_target = "#modal-container" })
        </div>
    }
    <!-- addReclaimModal -->
    <div id="modal-container" class="modal fade" tabindex="-1" style="border:5px solid #FF8000" role="dialog">
            <a href="#close" title="Cerrar" class="close modal-close-btn" type="button">X</a>
            <div class="modal-content" style="width:700px !important; height:400px !important; margin:10px auto !important">
                <div class="modal-body">                 
                </div>
            </div>
    </div>
    @if (ViewBag.ReclaimExists)
    {
        <div class="form-group">
            <h4>Reclamo</h4>
            @Html.Partial("_IndexReclaim", Model.Reclaims)
        </div>
        <div class="form-group">
            @Html.ActionLink("Agregar Comentario", "AddReclaimComment", "VisitHeaders", new { id = ViewBag.VisitHeaderId }, new { id = "addCommentLink", @class = "btn btn-default modal-link", title = "Agregar Comentario", data_toggle = "modal", data_target = "#modal-comment" })
        </div>
        <div class="form-group">
            <h4>Comentarios</h4>
            @Html.Partial("_IndexReclaimComments", Model.Reclaims.FirstOrDefault().ReclaimComment)
        </div>
    }


    <!-- addReclaimCommentModal -->
    <div id="modal-comment" class="modal fade" tabindex="-1" style="border:5px solid #FF8000" role="dialog">
        <a href="#close" title="Cerrar" class="close modal-close-btn" type="button">X</a>
        <div class="modal-content" style="width:700px !important; height:400px !important; margin:10px auto !important">
            <div class="modal-body">
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Volver al Listado", "Index")
    </p>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var status = '@ViewBag.StatusVisit';
        var reclaim = '@ViewBag.ReclaimExists';
        var isAdminOrCustomer = '@ViewBag.isAdminOrCustomer';
        if (status == '4' && reclaim == 'False' && isAdminOrCustomer == 'True')
            $('#addReclaimLink').click();
        if (status == '3')
            $('#')
    });


    $(function () {
        //Initialize modal dialog
        //Attach modal-container
        $('document').on('ready', '.modal-link', function (e) {
            e.preventDefault();
        });

        $('body').on('click', '.modal-close-btn', function () {
            $('#modal-container').modal('hide');
            $('#modal-comment').modal('hide');
        });
        $('#modal-container').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });
        $('#modal-comment').on('hidden.bs.modal', function () {
            $(this).removeData('bs.modal');
        });
    });

</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }

IndexaWeb.Intranet/Views/VisitHeaders/_CreateReclaim.cshtml
@model IndexaWeb.Intranet.Reclaim

<div class="">
    <div class="modal-title" style="color: #FF8000">
        <h3>Agregar Reclamo</h3>
    </div>
    <br />
    @using (Html.BeginForm("AddReclaim", "VisitHeaders", FormMethod.Post, new { id = "addReclaimForm" }))
    {
        @Html.AntiForgeryToken()
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VisitHeaderId)
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" id="btn-submit" class="btn btn-default">Agregar</button>
                    </div>
                </div>
    }
</div>
<script type="text/javascript">
    $(function () {
        $("#btn-submit").click(function () {
            $("#modal-container").modal("hide");
        })
    });
</script>





@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IndexaWeb.Intranet/Views/VisitHeaders/_CreateReclaimComment.cshtml
@model IndexaWeb.Intranet.ReclaimComment

<div class="">
    <div class="modal-title" style="color: #FF8000">
        <h3>Agregar Comentario</h3>
    </div>
    <br />
    @using (Html.BeginForm("AddReclaimComment", "VisitHeaders", FormMethod.Post, new { id = "addReclaimCommentForm" }))
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ReclaimId)
            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input id="btn-comment-submit" type="submit" value="Agregar" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    //$(function () {
    //    $("#btn-comment-submit").click(function () {
    //        $("#modal-container").modal("hide");
    //    })
    //});
</script>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

IndexaWeb.Intranet/Views/VisitHeaders/_CreateVisitDetails.cshtml
@model IndexaWeb.Intranet.VisitDetail

<div class="">
    <div class="modal-title" style="color: #FF8000">
        <h3>Agregar Actividad</h3>
    </div>
    <br />
    @using (Html.BeginForm("AddVisitDetail", "VisitHeaders", FormMethod.Post, new { id = "visitDetailForm" }))
    {
        @Html.AntiForgeryToken()
        <hr />
        <p>
            @Html.ActionLink("Registrar nueva Actividad", "Create", "Activities")
        </p>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.VisitHeaderId)
                <div class="form-group">
                    @Html.LabelFor(model => model.ActivityId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.ActivityId, (SelectList)ViewBag.Activities, "[Seleccione una Actividad]", new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ActivityId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TicketNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TicketNumber, new { htmlAttributes = new { @class = "form-control", type = "number" } })
                        @Html.ValidationMessageFor(model => model.TicketNumber, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.VisitNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.VisitNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.VisitNotes, "", new { @class = "text-danger" })
                    </div>
                </div>
                <hr />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" id="btn-submit" class="btn btn-default">Agregar</button>
                    </div>
                </div>
    }
</div>


<script type="text/javascript">
    $(function () {
        $("#btn-submit").click(function () {
            $("#modal-container").modal("hide");
        })
    });
</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IndexaWeb.Intranet/Views/VisitHeaders/_GetReclaimByVisit.cshtml
@model IEnumerable<IndexaWeb.Intranet.Reclaim>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
        </tr>
    }
</table>